#! /bin/bash
#
# Este script puede usarse para lanzar un proceso de gpu
# Se especifica la cola gpu, se solicita una gpu y se solicita 1G RAM para el proceso
#
# Para lanzarlo copielo a un directorio en su home y en ese directorio ejecute:
# qsub ejemploGPU
#
# Los procesos en la cola gpu tienen una duración máxima de 3 días
# Los procesos en la cola gpushort tienen una duración máxima de 20 minutos
#
# El sistema de cola devuelve una variable $SGE_GPU que contiene los IDs de los dispositivos requeridos (separados por coma). Ejemplo: 0 o 0,1 dependiendo del numero de recursos pedidos
# Use este device ID para cudaSetDevice()
#
# 
# Las lineas que comienzan con #$ son opciones para el sistema de cola
# Todas explicadas en el man qsub
#
#$ -cwd
#$ -j y
#$ -S /bin/bash
#$ -q gpu
#$ -l gpu=1
#$ -l memoria_a_usar=1G
#$ -N output_cpp_gpu_v1_evol
#
#cargar variables de entorno para encontrar cuda
module load cuda/10.0.130 


#compilo el programa
nvcc cpp_gpu_v1_simulacion_de_particulas.cu -o cpp_gpu_v1_simulacion_de_particulas

#ejecuto
#1 sola vez
./cpp_gpu_v1_simulacion_de_particulas 1000 1E-4 100000 1000
#varias veces
# for N in 2 5 10 20 50 100 200 500 1000 2000 5000 10000 20000; do ./cpp_gpu_v1_simulacion_de_particulas $N 1E-5 100 100; done

#Para hacer profiling
# nvprof -f ./cpp_gpu_v1_simulacion_de_particulas
